# aks-deployment-order.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 2 # Número de instancias que quieres correr
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        # MARCADOR DE POSICIÓN que Azure DevOps va a reemplazar con la imagen de ACR
        image: __IMAGE__ 
        ports:
        - containerPort: 8080 # Asegúrate que este puerto coincida con tu Dockerfile/Kestrel
---
# Definición de Service (para exponer el microservicio)
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  type: LoadBalancer # Para acceder desde fuera de AKS (si lo necesitas)
  ports:
  - port: 80 # Puerto externo de AKS
    targetPort: 8080 # Puerto interno del contenedor
  selector:
    app: order-service